# Site settings
title: brianweet
email: brianweeteling@gmail.com
description: >
  Hi, my name is Brian Weeteling. 
  I am a developer and CS master student at Leiden University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brianweet.github.io" # the base hostname & protocol for your site
github_username:  brianweet

# Build settings
markdown: redcarpet
