# Site settings
title: brianweet
email: brianweeteling@gmail.com
description: >
  Hi, my name is Brian Weeteling. 
  I am a passionate web developer :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.brianweet.com" # the base hostname & protocol for your site
github_username:  brianweet
future: false
env: production

# Build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
  style: compressed
