# Site settings
title: brianweet
email: brianweeteling@gmail.com
description: >
  Hi, my name is Brian Weeteling. 
  I am a web developer, currently studying CS at Leiden University. Dabbling with .NET, TypeScript, SPA's.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brianweet.github.io" # the base hostname & protocol for your site
github_username:  brianweet

# Build settings
markdown: kramdown

kramdown:
  input: GFM